---
driver_plugin: vagrant
platforms:
- name: centos-6.4-x86_64
  driver_config:
    box: opscode-centos-6.4-x86_64
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
    require_chef_omnibus: 11.4.4
    customize:
      cpus: 1
      memory: 256
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
    require_chef_omnibus: 11.4.4
    customize:
      cpus: 1
      memory: 256
suites:
- name: default
  run_list:
    - recipe[chromedriver]
